name: Run DFX hourly

on:
  schedule:
    - cron: "0 * * * *"   # 매 정시(UTC 기준) → KST는 +9시간
  workflow_dispatch:       # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: chrome

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.* gspread oauth2client

      - name: Write credentials.json from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Run script
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          python DFX.py
